// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestfestAPI.DatabaseContext;

#nullable disable

namespace TestfestAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TestfestAPI.Models.Comment", b =>
                {
                    b.Property<Guid>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IssueID")
                        .HasColumnType("char(36)");

                    b.HasKey("CommentID");

                    b.HasIndex("IssueID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("TestfestAPI.Models.Fix", b =>
                {
                    b.Property<Guid>("FixID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Instruksjon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("IssueID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("OpprettetDato")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Opprettet_av")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FixID");

                    b.HasIndex("IssueID")
                        .IsUnique();

                    b.ToTable("Fixes");
                });

            modelBuilder.Entity("TestfestAPI.Models.Issue", b =>
                {
                    b.Property<Guid>("IssueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Beskrivelse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FerdigBehandletDato")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("KanReteste")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("StatusID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("IssueID");

                    b.HasIndex("StatusID");

                    b.HasIndex("UserID");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("TestfestAPI.Models.Status", b =>
                {
                    b.Property<Guid>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Beskrivelse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StatusID");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusID = new Guid("00000000-0000-0000-0000-000000000001"),
                            Beskrivelse = "Sak mottatt"
                        },
                        new
                        {
                            StatusID = new Guid("00000000-0000-0000-0000-000000000002"),
                            Beskrivelse = "Under behandling"
                        },
                        new
                        {
                            StatusID = new Guid("00000000-0000-0000-0000-000000000003"),
                            Beskrivelse = "Ferdigbehandlet/lukket"
                        });
                });

            modelBuilder.Entity("TestfestAPI.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("GithubID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Rolle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserID");

                    b.HasIndex("GithubID")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TestfestAPI.Models.Comment", b =>
                {
                    b.HasOne("TestfestAPI.Models.Issue", "Issue")
                        .WithMany("Comments")
                        .HasForeignKey("IssueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("TestfestAPI.Models.Fix", b =>
                {
                    b.HasOne("TestfestAPI.Models.Issue", "Issue")
                        .WithOne("Fix")
                        .HasForeignKey("TestfestAPI.Models.Fix", "IssueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("TestfestAPI.Models.Issue", b =>
                {
                    b.HasOne("TestfestAPI.Models.Status", "Status")
                        .WithMany("Issues")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestfestAPI.Models.User", "User")
                        .WithMany("Issues")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TestfestAPI.Models.Issue", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Fix");
                });

            modelBuilder.Entity("TestfestAPI.Models.Status", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("TestfestAPI.Models.User", b =>
                {
                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
